"""totp_recovery_codes

Revision ID: 15745463cdad
Revises: b2d4cc7dbe00
Create Date: 2026-05-15 00:05:04.048842

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '15745463cdad'
down_revision: str | Sequence[str] | None = 'b2d4cc7dbe00'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_totp_recovery_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_totp_recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_totp_recovery_codes_code_hash'), ['code_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_totp_recovery_codes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_totp_recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_totp_recovery_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_totp_recovery_codes_code_hash'))

    op.drop_table('user_totp_recovery_codes')
    # ### end Alembic commands ###
