"""shift rules

Revision ID: 2823730c4ea4
Revises: 598bccf9f7db
Create Date: 2026-05-14 21:51:32.188756

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2823730c4ea4'
down_revision: str | Sequence[str] | None = '598bccf9f7db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('late_grace_minutes', sa.Integer(), nullable=False),
    sa.Column('early_out_grace_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_threshold_minutes', sa.Integer(), nullable=False),
    sa.Column('work_days', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_rule_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_employees_shift_rule_id'), ['shift_rule_id'], unique=False)
        # SQLite's batch_alter_table needs a named constraint — alembic
        # autogenerate emits `None` by default.
        batch_op.create_foreign_key(
            'fk_employees_shift_rule_id',
            'shift_rules',
            ['shift_rule_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employees_shift_rule_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_employees_shift_rule_id'))
        batch_op.drop_column('shift_rule_id')

    op.drop_table('shift_rules')
    # ### end Alembic commands ###
