"""initial schema

Revision ID: 8c51c515c891
Revises:
Create Date: 2026-05-14 20:40:46.223158

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8c51c515c891'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('poll_interval_sec', sa.Integer(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_serial_number'), ['serial_number'], unique=True)

    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_code', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_employee_code'), ['employee_code'], unique=True)

    op.create_table('attendance_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('device_user_id', sa.String(length=64), nullable=False),
    sa.Column('punched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('punch_type', sa.Integer(), nullable=False),
    sa.Column('verify_mode', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'device_user_id', 'punched_at', name='uq_attendance_logs_device_user_time')
    )
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_logs_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_logs_device_user_id'), ['device_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_logs_punched_at'), ['punched_at'], unique=False)

    op.create_table('employee_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('source_device_id', sa.String(length=36), nullable=False),
    sa.Column('finger_id', sa.Integer(), nullable=False),
    sa.Column('template_data', sa.LargeBinary(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['source_device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'source_device_id', 'finger_id', name='uq_employee_template_triple')
    )
    with op.batch_alter_table('employee_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_templates_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_templates_source_device_id'), ['source_device_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_employee_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('employee_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_templates_source_device_id'))
        batch_op.drop_index(batch_op.f('ix_employee_templates_employee_id'))

    op.drop_table('employee_templates')
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_logs_punched_at'))
        batch_op.drop_index(batch_op.f('ix_attendance_logs_device_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_logs_device_id'))

    op.drop_table('attendance_logs')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_employee_code'))

    op.drop_table('employees')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_serial_number'))

    op.drop_table('devices')
    # ### end Alembic commands ###
