"""user_totp

Revision ID: b2d4cc7dbe00
Revises: 2823730c4ea4
Create Date: 2026-05-14 22:44:26.620996

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b2d4cc7dbe00'
down_revision: str | Sequence[str] | None = '2823730c4ea4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_totp',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('secret_b32', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_totp')
    # ### end Alembic commands ###
